data:
  cadenza_data_root: /home/austin/clarity-dolphin-bear/recipes/cad_icassp_2026/baseline
  dataset: cadenza_data
  sample_rate: 44100  # Sample rate of the audio files


# Hydra parameters
hydra:
  run:
    dir: exp
  job:
    chdir: True