defaults:
  - _self_
  - common
  - baseline: whisper  # stoi or whisper or features

split: valid
resume_checkpoint: ./cadenza_data.train.simple_meanpool_scalar_mlp.epoch50.pth
model_type: simple_meanpool_scalar_mlp